#!/bin/bash
# ==============================================================================
# DO NOT EDIT THIS FILE
# This is an internal execution script called by submit.py.
# ==============================================================================
set -e

if [ -f "$VVM_ENV_SCRIPT" ]; then
    echo "Sourcing environment from: $VVM_ENV_SCRIPT"
    source "$VVM_ENV_SCRIPT"
else
    echo "[Error] Environment script not found: $VVM_ENV_SCRIPT"
    exit 1
fi

export OMP_NUM_THREADS=${OMP_NUM_THREADS:-1}

VVM_ARGS=""
if [ "$VVM_IO_ENGINE" == "SST" ]; then
    VVM_ARGS="--io-tasks $VVM_IO_TASKS"
fi

echo "Starting VVM..."
mpirun -np $VVM_TOTAL_TASKS \
 -x NCCL_DEBUG=INFO \
 -x HDF5_USE_FILE_LOCKING=FALSE \
 --mca io ompio \
 --mca sharedfp ^lockedfile,individual \
 ./build/vvm "$VVM_CONFIG_FILE" $VVM_ARGS
