#!/bin/bash
# ==============================================================================
# DO NOT EDIT THIS FILE
# This is an internal execution script called by submit.py.
# ==============================================================================
set -e

if [ -f "$VVM_ENV_SCRIPT" ]; then
    source "$VVM_ENV_SCRIPT"
fi

TASKS_PER_NODE=$(( VVM_COMPUTE_PER_NODE + VVM_IO_PER_NODE ))

if [ -n "$SLURM_JOB_ID" ]; then
    if [ -n "$SLURM_JOB_CPUS_PER_NODE" ]; then
        TOTAL_CORES=$(echo $SLURM_JOB_CPUS_PER_NODE | awk -F'[(x]' '{print $1}')
    else
        TOTAL_CORES=$(nproc --all)
    fi
    PE=$(( TOTAL_CORES / TASKS_PER_NODE ))
    if [ "$PE" -lt 1 ]; then PE=1; fi
    RUN_MODE="SLURM Auto-Tuning"
else
    PE=${OMP_NUM_THREADS:-1}
    TOTAL_CORES=$(( PE * TASKS_PER_NODE ))
    RUN_MODE="Local Shared Mode"
fi

echo "========================================================="
echo "[$RUN_MODE]"
echo " Nodes: ${SLURM_JOB_NUM_NODES:-1} | Tasks/Node: $TASKS_PER_NODE"
echo " Total Cores Used/Node: $TOTAL_CORES | Allocated Cores/Task (PE): $PE"
echo "========================================================="

VVM_ARGS=""
if [ "$VVM_IO_ENGINE" == "SST" ]; then
    VVM_ARGS="--io-tasks $VVM_IO_TASKS"
fi

mpirun -np $VVM_TOTAL_TASKS \
 --map-by ppr:${TASKS_PER_NODE}:node:PE=${PE} \
 -x OMP_NUM_THREADS=${PE} \
 -x OMP_PROC_BIND=close \
 -x OMP_PLACES=cores \
 -x NCCL_DEBUG=INFO \
 -x HDF5_USE_FILE_LOCKING=FALSE \
 -x VVM_GPUS \
 -x VVM_COMPUTE_PER_NODE \
 ./tools/vvm_wrapper.sh ./build/vvm "$VVM_CONFIG_FILE" $VVM_ARGS
