#!/bin/bash
# ==============================================================================
# DO NOT EDIT THIS FILE
# This is an internal execution script called by core.sh
# ==============================================================================

export CUDA_VISIBLE_DEVICES=$(( OMPI_COMM_WORLD_LOCAL_RANK % VVM_GPUS ))

exec "$@"
